const EVENTS = {
  RECEIVE_AUDIO_URL: 'RECEIVE_AUDIO_URL',
  TOGGLE_AUDIO_MODE: 'TOGGLE_AUDIO_MODE',
  REQUEST_AUDIO_MODE_STATUS: 'REQUEST_AUDIO_MODE_STATUS：',
  UI_START_AUDIO_MODE: 'UI_START_AUDIO_MODE',
  UI_STOP_AUDIO_MODE: 'UI_STOP_AUDIO_MODE',
  UI_RECEIVE_AUDIO_URL: 'UI_RECEIVE_AUDIO_URL',
};

export default EVENTS;
