const EVENTS = {
  GET_YOUTUBE_REQUEST_SERVICE_STATE: 'GET_YOUTUBE_REQUEST_SERVICE_STATE',
  SET_YOUTUBE_REQUEST_SERVICE_STATE: 'SET_YOUTUBE_REQUEST_SERVICE_STATE',
  SET_AUDIO_MODE_SERVICE_STATE: 'SET_AUDIO_MODE_SERVICE_STATE',
};

export default EVENTS;
